# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import python.trainer.env.snake_env_pb2 as snake__env__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snake_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SnakeEnvStub(object):
    """SnakeEnv defines a simple episodic environment for Snake.
    The Python RL trainer will treat this like a remote Gym-style env.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/serpentlab.SnakeEnv/Reset',
                request_serializer=snake__env__pb2.ResetRequest.SerializeToString,
                response_deserializer=snake__env__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/serpentlab.SnakeEnv/Step',
                request_serializer=snake__env__pb2.StepRequest.SerializeToString,
                response_deserializer=snake__env__pb2.StepResponse.FromString,
                _registered_method=True)


class SnakeEnvServicer(object):
    """SnakeEnv defines a simple episodic environment for Snake.
    The Python RL trainer will treat this like a remote Gym-style env.
    """

    def Reset(self, request, context):
        """Reset starts a new episode (or restarts an existing session).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Step advances the environment one tick with the given action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnakeEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=snake__env__pb2.ResetRequest.FromString,
                    response_serializer=snake__env__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=snake__env__pb2.StepRequest.FromString,
                    response_serializer=snake__env__pb2.StepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serpentlab.SnakeEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serpentlab.SnakeEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnakeEnv(object):
    """SnakeEnv defines a simple episodic environment for Snake.
    The Python RL trainer will treat this like a remote Gym-style env.
    """

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serpentlab.SnakeEnv/Reset',
            snake__env__pb2.ResetRequest.SerializeToString,
            snake__env__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serpentlab.SnakeEnv/Step',
            snake__env__pb2.StepRequest.SerializeToString,
            snake__env__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
