# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snake_env.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'snake_env.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsnake_env.proto\x12\nserpentlab\"U\n\x0cResetRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nwith_walls\x18\x04 \x01(\x08\"m\n\rResetResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04grid\x18\x02 \x03(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x05\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\"1\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\"|\n\x0cStepResponse\x12\x0c\n\x04grid\x18\x01 \x03(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\r\n\x05score\x18\x06 \x01(\x05\x12\x12\n\nstep_index\x18\x07 \x01(\x05\x32\x83\x01\n\x08SnakeEnv\x12<\n\x05Reset\x12\x18.serpentlab.ResetRequest\x1a\x19.serpentlab.ResetResponse\x12\x39\n\x04Step\x12\x17.serpentlab.StepRequest\x1a\x18.serpentlab.StepResponseB<Z:github.com/stevenmed26/SerpentLab/internal/grpcapi;grpcapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snake_env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/stevenmed26/SerpentLab/internal/grpcapi;grpcapi'
  _globals['_RESETREQUEST']._serialized_start=31
  _globals['_RESETREQUEST']._serialized_end=116
  _globals['_RESETRESPONSE']._serialized_start=118
  _globals['_RESETRESPONSE']._serialized_end=227
  _globals['_STEPREQUEST']._serialized_start=229
  _globals['_STEPREQUEST']._serialized_end=278
  _globals['_STEPRESPONSE']._serialized_start=280
  _globals['_STEPRESPONSE']._serialized_end=404
  _globals['_SNAKEENV']._serialized_start=407
  _globals['_SNAKEENV']._serialized_end=538
# @@protoc_insertion_point(module_scope)
