// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/snake_env.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeathCause int32

const (
	DeathCause_DEATH_CAUSE_UNSPECIFIED DeathCause = 0
	DeathCause_DEATH_CAUSE_WALL        DeathCause = 1
	DeathCause_DEATH_CAUSE_SELF        DeathCause = 2
	DeathCause_DEATH_CAUSE_STALL       DeathCause = 3
)

// Enum value maps for DeathCause.
var (
	DeathCause_name = map[int32]string{
		0: "DEATH_CAUSE_UNSPECIFIED",
		1: "DEATH_CAUSE_WALL",
		2: "DEATH_CAUSE_SELF",
		3: "DEATH_CAUSE_STALL",
	}
	DeathCause_value = map[string]int32{
		"DEATH_CAUSE_UNSPECIFIED": 0,
		"DEATH_CAUSE_WALL":        1,
		"DEATH_CAUSE_SELF":        2,
		"DEATH_CAUSE_STALL":       3,
	}
)

func (x DeathCause) Enum() *DeathCause {
	p := new(DeathCause)
	*p = x
	return p
}

func (x DeathCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeathCause) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_snake_env_proto_enumTypes[0].Descriptor()
}

func (DeathCause) Type() protoreflect.EnumType {
	return &file_proto_snake_env_proto_enumTypes[0]
}

func (x DeathCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeathCause.Descriptor instead.
func (DeathCause) EnumDescriptor() ([]byte, []int) {
	return file_proto_snake_env_proto_rawDescGZIP(), []int{0}
}

// ResetRequest optionally specifies configuration overrides for the new episode.
// session_id is optional; if empty, the server can generate one and return it.
type ResetRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional per-episode config (can be zero to use server defaults).
	Width         int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	WithWalls     bool  `protobuf:"varint,4,opt,name=with_walls,json=withWalls,proto3" json:"with_walls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_snake_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_snake_env_proto_rawDescGZIP(), []int{0}
}

func (x *ResetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResetRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResetRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResetRequest) GetWithWalls() bool {
	if x != nil {
		return x.WithWalls
	}
	return false
}

// ResetResponse returns the initial state of the environment.
type ResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session_id that will be used for subsequent Step calls.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Flattened grid of size width * height.
	// 0 = empty, 1 = snake, 2 = food, 3 = wall
	Grid   []int32 `protobuf:"varint,2,rep,packed,name=grid,proto3" json:"grid,omitempty"`
	Width  int32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Score at the start of the episode (usually 0).
	Score int32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	// Episodes always start not-done, but included for consistency.
	Done          bool `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_proto_snake_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_snake_env_proto_rawDescGZIP(), []int{1}
}

func (x *ResetResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResetResponse) GetGrid() []int32 {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *ResetResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResetResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResetResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ResetResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// StepRequest advances the current episode by one action.
type StepRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 0 = up, 1 = right, 2 = down, 3 = left
	Action        int32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_proto_snake_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_proto_snake_env_proto_rawDescGZIP(), []int{2}
}

func (x *StepRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StepRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// StepResponse returns the new state after the action.
type StepResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Grid   []int32                `protobuf:"varint,1,rep,packed,name=grid,proto3" json:"grid,omitempty"`
	Width  int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Whether this step ended the episode (death).
	Done bool `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	// Current cumulative score for this episode.
	Score int32 `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	// Optional: number of steps taken so far in this episode.
	StepIndex      int32      `protobuf:"varint,7,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	DeathCause     DeathCause `protobuf:"varint,9,opt,name=death_cause,json=deathCause,proto3,enum=serpentlab.DeathCause" json:"death_cause,omitempty"`
	DeltaDist      string     `protobuf:"bytes,10,opt,name=delta_dist,json=deltaDist,proto3" json:"delta_dist,omitempty"`
	AteFood        bool       `protobuf:"varint,11,opt,name=ate_food,json=ateFood,proto3" json:"ate_food,omitempty"`
	StepsSinceFood int32      `protobuf:"varint,12,opt,name=steps_since_food,json=stepsSinceFood,proto3" json:"steps_since_food,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_proto_snake_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_proto_snake_env_proto_rawDescGZIP(), []int{3}
}

func (x *StepResponse) GetGrid() []int32 {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *StepResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StepResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StepResponse) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *StepResponse) GetDeathCause() DeathCause {
	if x != nil {
		return x.DeathCause
	}
	return DeathCause_DEATH_CAUSE_UNSPECIFIED
}

func (x *StepResponse) GetDeltaDist() string {
	if x != nil {
		return x.DeltaDist
	}
	return ""
}

func (x *StepResponse) GetAteFood() bool {
	if x != nil {
		return x.AteFood
	}
	return false
}

func (x *StepResponse) GetStepsSinceFood() int32 {
	if x != nil {
		return x.StepsSinceFood
	}
	return 0
}

var File_proto_snake_env_proto protoreflect.FileDescriptor

const file_proto_snake_env_proto_rawDesc = "" +
	"\n" +
	"\x15proto/snake_env.proto\x12\n" +
	"serpentlab\"z\n" +
	"\fResetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"with_walls\x18\x04 \x01(\bR\twithWalls\"\x9a\x01\n" +
	"\rResetResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04grid\x18\x02 \x03(\x05R\x04grid\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x12\n" +
	"\x04done\x18\x06 \x01(\bR\x04done\"D\n" +
	"\vStepRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\"\xb6\x02\n" +
	"\fStepResponse\x12\x12\n" +
	"\x04grid\x18\x01 \x03(\x05R\x04grid\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"step_index\x18\a \x01(\x05R\tstepIndex\x127\n" +
	"\vdeath_cause\x18\t \x01(\x0e2\x16.serpentlab.DeathCauseR\n" +
	"deathCause\x12\x1d\n" +
	"\n" +
	"delta_dist\x18\n" +
	" \x01(\tR\tdeltaDist\x12\x19\n" +
	"\bate_food\x18\v \x01(\bR\aateFood\x12(\n" +
	"\x10steps_since_food\x18\f \x01(\x05R\x0estepsSinceFood*l\n" +
	"\n" +
	"DeathCause\x12\x1b\n" +
	"\x17DEATH_CAUSE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEATH_CAUSE_WALL\x10\x01\x12\x14\n" +
	"\x10DEATH_CAUSE_SELF\x10\x02\x12\x15\n" +
	"\x11DEATH_CAUSE_STALL\x10\x032\x83\x01\n" +
	"\bSnakeEnv\x12<\n" +
	"\x05Reset\x12\x18.serpentlab.ResetRequest\x1a\x19.serpentlab.ResetResponse\x129\n" +
	"\x04Step\x12\x17.serpentlab.StepRequest\x1a\x18.serpentlab.StepResponseB<Z:github.com/stevenmed26/serpentlab/internal/grpcapi;grpcapib\x06proto3"

var (
	file_proto_snake_env_proto_rawDescOnce sync.Once
	file_proto_snake_env_proto_rawDescData []byte
)

func file_proto_snake_env_proto_rawDescGZIP() []byte {
	file_proto_snake_env_proto_rawDescOnce.Do(func() {
		file_proto_snake_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_snake_env_proto_rawDesc), len(file_proto_snake_env_proto_rawDesc)))
	})
	return file_proto_snake_env_proto_rawDescData
}

var file_proto_snake_env_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_snake_env_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_snake_env_proto_goTypes = []any{
	(DeathCause)(0),       // 0: serpentlab.DeathCause
	(*ResetRequest)(nil),  // 1: serpentlab.ResetRequest
	(*ResetResponse)(nil), // 2: serpentlab.ResetResponse
	(*StepRequest)(nil),   // 3: serpentlab.StepRequest
	(*StepResponse)(nil),  // 4: serpentlab.StepResponse
}
var file_proto_snake_env_proto_depIdxs = []int32{
	0, // 0: serpentlab.StepResponse.death_cause:type_name -> serpentlab.DeathCause
	1, // 1: serpentlab.SnakeEnv.Reset:input_type -> serpentlab.ResetRequest
	3, // 2: serpentlab.SnakeEnv.Step:input_type -> serpentlab.StepRequest
	2, // 3: serpentlab.SnakeEnv.Reset:output_type -> serpentlab.ResetResponse
	4, // 4: serpentlab.SnakeEnv.Step:output_type -> serpentlab.StepResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_snake_env_proto_init() }
func file_proto_snake_env_proto_init() {
	if File_proto_snake_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_snake_env_proto_rawDesc), len(file_proto_snake_env_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_snake_env_proto_goTypes,
		DependencyIndexes: file_proto_snake_env_proto_depIdxs,
		EnumInfos:         file_proto_snake_env_proto_enumTypes,
		MessageInfos:      file_proto_snake_env_proto_msgTypes,
	}.Build()
	File_proto_snake_env_proto = out.File
	file_proto_snake_env_proto_goTypes = nil
	file_proto_snake_env_proto_depIdxs = nil
}
