// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/snake_env.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnakeEnv_Reset_FullMethodName = "/serpentlab.SnakeEnv/Reset"
	SnakeEnv_Step_FullMethodName  = "/serpentlab.SnakeEnv/Step"
)

// SnakeEnvClient is the client API for SnakeEnv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnakeEnv defines a simple episodic environment for Snake.
// The Python RL trainer will treat this like a remote Gym-style env.
type SnakeEnvClient interface {
	// Reset starts a new episode (or restarts an existing session).
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Step advances the environment one tick with the given action.
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
}

type snakeEnvClient struct {
	cc grpc.ClientConnInterface
}

func NewSnakeEnvClient(cc grpc.ClientConnInterface) SnakeEnvClient {
	return &snakeEnvClient{cc}
}

func (c *snakeEnvClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, SnakeEnv_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snakeEnvClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, SnakeEnv_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnakeEnvServer is the server API for SnakeEnv service.
// All implementations must embed UnimplementedSnakeEnvServer
// for forward compatibility.
//
// SnakeEnv defines a simple episodic environment for Snake.
// The Python RL trainer will treat this like a remote Gym-style env.
type SnakeEnvServer interface {
	// Reset starts a new episode (or restarts an existing session).
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// Step advances the environment one tick with the given action.
	Step(context.Context, *StepRequest) (*StepResponse, error)
	mustEmbedUnimplementedSnakeEnvServer()
}

// UnimplementedSnakeEnvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnakeEnvServer struct{}

func (UnimplementedSnakeEnvServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSnakeEnvServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedSnakeEnvServer) mustEmbedUnimplementedSnakeEnvServer() {}
func (UnimplementedSnakeEnvServer) testEmbeddedByValue()                  {}

// UnsafeSnakeEnvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnakeEnvServer will
// result in compilation errors.
type UnsafeSnakeEnvServer interface {
	mustEmbedUnimplementedSnakeEnvServer()
}

func RegisterSnakeEnvServer(s grpc.ServiceRegistrar, srv SnakeEnvServer) {
	// If the following call pancis, it indicates UnimplementedSnakeEnvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnakeEnv_ServiceDesc, srv)
}

func _SnakeEnv_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnakeEnvServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnakeEnv_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnakeEnvServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnakeEnv_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnakeEnvServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnakeEnv_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnakeEnvServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnakeEnv_ServiceDesc is the grpc.ServiceDesc for SnakeEnv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnakeEnv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serpentlab.SnakeEnv",
	HandlerType: (*SnakeEnvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _SnakeEnv_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _SnakeEnv_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/snake_env.proto",
}
